version: '3.9'

services:
  auth-db:
    image: postgres:16
    container_name: auth-db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d auth-db'" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 50

  redis:
    image: redis:latest
    container_name: auth-redis
    ports:
      - "6379:6379"
